dist: bionic
language: minimal

env:
  - SHARDS_OPTS=--ignore-crystal-version

install:
  - curl -fsSL https://crystal-lang.org/install.sh | sudo bash

before_script:
  - shards install

script:
  - crystal tool format --check
  - |
    crystal spec ./spec/core &&
    crystal spec ./spec/amber &&
    crystal spec ./spec/lucky &&
    crystal spec ./spec/spider-gazelle
